export type ProductSpecificationItem = {
  label: string;
  value: string;
};

export type ProductSpecificationGroup = {
  title: string;
  items: ProductSpecificationItem[];
};

export type ProductSpecificationRecord = {
  sourceUrl: string;
  sourceModel: string;
  sourceLocale: string;
  verifiedAt: string;
  status: "verified" | "unverified";
  groups: ProductSpecificationGroup[];
  note?: string;
};

const VERIFIED_AT = "2026-08-12";

function verifiedRecord(
  sourceUrl: string,
  sourceModel: string,
  items: ProductSpecificationItem[],
  options: { sourceLocale?: string; note?: string; groupTitle?: string } = {},
): ProductSpecificationRecord {
  return {
    sourceUrl,
    sourceModel,
    sourceLocale: options.sourceLocale ?? "th-TH",
    verifiedAt: VERIFIED_AT,
    status: "verified",
    groups: [
      {
        title: options.groupTitle ?? "ข้อมูลจำเพาะสำคัญ",
        items,
      },
    ],
    ...(options.note ? { note: options.note } : {}),
  };
}

export const productSpecificationRecords: Record<string, ProductSpecificationRecord> = {
  ART13A: verifiedRecord(
    "https://www.lg.com/th/air-conditioner-inverter/energy-saving-air-conditioner/art13a/",
    "ART13A.SR1",
    [
      { label: "ขนาดการทำความเย็น", value: "11,942 BTU" },
      { label: "ประเภท", value: "ติดผนัง ARTCOOL" },
      { label: "กำลังทำความเย็นพิกัด / ต่ำสุด", value: "3,500 / 630 วัตต์" },
      { label: "กำลังไฟฟ้าพิกัด / ต่ำสุด", value: "850 / 200 วัตต์" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "895 × 307 × 235 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "770 × 545 × 288 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "5 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  ART18A: verifiedRecord(
    "https://www.lg.com/th/air-conditioner-inverter/energy-saving-air-conditioner/art18a/",
    "ART18A.SR1",
    [
      { label: "ขนาดการทำความเย็น", value: "18,084 BTU" },
      { label: "ประเภท", value: "ติดผนัง ARTCOOL" },
      { label: "กำลังทำความเย็นพิกัด / ต่ำสุด", value: "5,300 / 940 วัตต์" },
      { label: "กำลังไฟฟ้าพิกัด / ต่ำสุด", value: "1,450 / 270 วัตต์" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "935 × 307 × 235 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "870 × 650 × 330 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "3 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  SAQ11A: verifiedRecord(
    "https://www.lg.com/th/air-conditioner-inverter/energy-saving-air-conditioner/saq11a/",
    "SAQ11A",
    [
      { label: "ขนาดการทำความเย็น", value: "9,200 BTU" },
      { label: "กำลังทำความเย็นพิกัด / ต่ำสุด", value: "2,696 / 630 วัตต์" },
      { label: "กำลังไฟฟ้าพิกัด / ต่ำสุด", value: "580 / 200 วัตต์" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "895 × 307 × 235 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "770 × 545 × 288 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "5 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  SAQ13A: verifiedRecord(
    "https://www.lg.com/th/air-conditioner-inverter/energy-saving-air-conditioner/saq13a/",
    "SAQ13A",
    [
      { label: "ขนาดการทำความเย็น", value: "12,000 BTU" },
      { label: "กำลังทำความเย็นพิกัด / ต่ำสุด", value: "3,517 / 630 วัตต์" },
      { label: "กำลังไฟฟ้าพิกัด / ต่ำสุด", value: "850 / 200 วัตต์" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "895 × 307 × 235 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "770 × 545 × 288 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "5 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  SAQ18B: verifiedRecord(
    "https://www.lg.com/th/air-conditioner-inverter/energy-saving-air-conditioner/saq18b/",
    "SAQ18B",
    [
      { label: "ขนาดการทำความเย็น", value: "18,084 BTU" },
      { label: "กำลังทำความเย็นพิกัด / ต่ำสุด", value: "5,300 / 938 วัตต์" },
      { label: "กำลังไฟฟ้าพิกัด / ต่ำสุด", value: "1,300 / 270 วัตต์" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "1,050 × 307 × 235 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "870 × 650 × 330 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "5 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  SAQ24B: verifiedRecord(
    "https://www.lg.com/th/air-conditioner-inverter/energy-saving-air-conditioner/saq24b/",
    "SAQ24B",
    [
      { label: "ขนาดการทำความเย็น", value: "24,225 BTU" },
      { label: "กำลังทำความเย็นพิกัด / ต่ำสุด", value: "7,100 / 938 วัตต์" },
      { label: "กำลังไฟฟ้าพิกัด / ต่ำสุด", value: "2,020 / 200 วัตต์" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "1,050 × 307 × 235 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "870 × 650 × 330 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "4 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  SIQ11B: verifiedRecord(
    "https://www.lg.com/th/air-conditioner-inverter/air-conditioner-with-air-purifier/siq11b/",
    "SIQ11B",
    [
      { label: "ขนาดการทำความเย็น", value: "9,212 BTU" },
      { label: "กำลังทำความเย็นพิกัด / ต่ำสุด", value: "2,700 / 1,000 วัตต์" },
      { label: "กำลังไฟฟ้าพิกัด / ต่ำสุด", value: "810 / 200 วัตต์" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "799 × 307 × 235 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "717 × 495 × 230 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "1 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  SIQ13B: verifiedRecord(
    "https://www.lg.com/th/air-conditioner-inverter/air-conditioner-with-air-purifier/siq13b/",
    "SIQ13B",
    [
      { label: "ขนาดการทำความเย็น", value: "12,283 BTU" },
      { label: "กำลังทำความเย็นพิกัด / ต่ำสุด", value: "3,600 / 645 วัตต์" },
      { label: "กำลังไฟฟ้าพิกัด / ต่ำสุด", value: "1,150 / 200 วัตต์" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "799 × 307 × 235 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "717 × 495 × 230 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "1 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  SIQ18B: verifiedRecord(
    "https://www.lg.com/th/air-conditioner-inverter/air-conditioner-with-air-purifier/siq18b/",
    "SIQ18B",
    [
      { label: "ขนาดการทำความเย็น", value: "18,084 BTU" },
      { label: "กำลังทำความเย็นพิกัด / ต่ำสุด", value: "5,300 / 938 วัตต์" },
      { label: "กำลังไฟฟ้าพิกัด / ต่ำสุด", value: "1,715 / 250 วัตต์" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "895 × 307 × 235 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "770 × 545 × 288 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "1 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  SIQ24B: verifiedRecord(
    "https://www.lg.com/th/air-conditioner-inverter/air-conditioner-with-air-purifier/siq24b/",
    "SIQ24B",
    [
      { label: "ขนาดการทำความเย็น", value: "22,178 BTU" },
      { label: "กำลังทำความเย็นพิกัด / ต่ำสุด", value: "6,500 / 938 วัตต์" },
      { label: "กำลังไฟฟ้าพิกัด / ต่ำสุด", value: "2,000 / 200 วัตต์" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "895 × 307 × 235 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "870 × 650 × 330 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "1 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  ZT4Q18GPLA1: verifiedRecord(
    "https://www.lg.com/th/business/hvac/commercial-solutions/single-split/ceiling-mounted-cassette/",
    "ZT4Q18GPLA1.EWGHATH",
    [
      { label: "ประเภท", value: "แอร์ฝังฝ้า 4 ทิศทาง" },
      { label: "ขนาดการทำความเย็น", value: "18,000 BTU" },
      { label: "SEER", value: "19.04" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "840 × 204 × 840 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "717 × 483 × 230 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "1 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
    ],
  ),
  ZT4Q24GPLA1: verifiedRecord(
    "https://www.lg.com/th/business/hvac/commercial-solutions/single-split/ceiling-mounted-cassette/",
    "ZT4Q24GPLA1.EWGHATH",
    [
      { label: "ประเภท", value: "แอร์ฝังฝ้า 4 ทิศทาง" },
      { label: "ขนาดการทำความเย็น", value: "24,500 BTU" },
      { label: "SEER", value: "19.11" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "840 × 204 × 840 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "870 × 650 × 330 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "1 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
    ],
  ),
  ZT4Q36GNLA1: verifiedRecord(
    "https://www.lg.com/th/business/hvac/commercial-solutions/single-split/ceiling-mounted-cassette/",
    "ZT4Q36GNLA1.EWGHATH",
    [
      { label: "ประเภท", value: "แอร์ฝังฝ้า 4 ทิศทาง" },
      { label: "ขนาดการทำความเย็น", value: "36,200 BTU" },
      { label: "SEER", value: "18.07" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "840 × 246 × 840 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "950 × 834 × 330 มม." },
      { label: "ไฟฟ้า", value: "220 โวลต์ 1 เฟส" },
      { label: "ระดับประหยัดพลังงาน", value: "1 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
    ],
  ),
  ZT4Q48GMLA1: verifiedRecord(
    "https://www.lg.com/th/business/hvac/commercial-solutions/single-split/ceiling-mounted-cassette/",
    "ZT4Q48GMLA1.EWGHATH",
    [
      { label: "ประเภท", value: "แอร์ฝังฝ้า 4 ทิศทาง" },
      { label: "ขนาดการทำความเย็น", value: "48,000 BTU" },
      { label: "SEER", value: "17.60" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "840 × 288 × 840 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "950 × 834 × 330 มม." },
      { label: "ไฟฟ้า", value: "220 โวลต์ 1 เฟส" },
      { label: "ระดับประหยัดพลังงาน", value: "2 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
    ],
  ),
  ZT1Q12GULA1: verifiedRecord(
    "https://www.lg.com/th/business/hvac/commercial-solutions/single-split/",
    "ZT1Q12GULA1.EWGHATH",
    [
      { label: "ประเภท", value: "แอร์ฝังฝ้า 1 ทิศทาง" },
      { label: "ขนาดการทำความเย็น", value: "10,500 BTU" },
      { label: "SEER", value: "18.05" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "860 × 132 × 450 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "717 × 483 × 230 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "1 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
    ],
  ),
  ZT1Q18GTLA1: verifiedRecord(
    "https://www.lg.com/th/business/hvac/commercial-solutions/single-split/",
    "ZT1Q18GTLA1.EWGHATH",
    [
      { label: "ประเภท", value: "แอร์ฝังฝ้า 1 ทิศทาง" },
      { label: "ขนาดการทำความเย็น", value: "18,000 BTU" },
      { label: "SEER", value: "17.92" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "1,180 × 132 × 450 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "770 × 545 × 288 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "1 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
    ],
  ),
  ZT1Q24GTLA1: verifiedRecord(
    "https://www.lg.com/th/business/hvac/commercial-solutions/single-split/",
    "ZT1Q24GTLA1.EWGHATH",
    [
      { label: "ประเภท", value: "แอร์ฝังฝ้า 1 ทิศทาง" },
      { label: "ขนาดการทำความเย็น", value: "23,500 BTU" },
      { label: "SEER", value: "17.61" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "1,180 × 132 × 450 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "870 × 650 × 330 มม." },
      { label: "ระดับประหยัดพลังงาน", value: "1 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
    ],
  ),
  ZTRQ36GYLA1: verifiedRecord(
    "https://www.lg.com/th/business/hvac/commercial-solutions/single-split/round-cassette/",
    "ZTRQ36GYLA1.EWGHATH",
    [
      { label: "ประเภท", value: "แอร์ฝังฝ้าวงกลม (คาสเซ็ทรอบทิศทาง)" },
      { label: "ขนาดการทำความเย็น", value: "36,700 BTU" },
      { label: "SEER", value: "19.28" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "1,050 × 330 × 1,050 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "950 × 834 × 330 มม." },
      { label: "ไฟฟ้า", value: "220 โวลต์ 1 เฟส" },
      { label: "ระดับประหยัดพลังงาน", value: "2 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
    ],
  ),
  ZTRQ48GYLA1: verifiedRecord(
    "https://www.lg.com/th/business/hvac/commercial-solutions/single-split/round-cassette/",
    "ZTRQ48GYLA1.EWGHATH",
    [
      { label: "ประเภท", value: "แอร์ฝังฝ้าวงกลม (คาสเซ็ทรอบทิศทาง)" },
      { label: "ขนาดการทำความเย็น", value: "47,300 BTU" },
      { label: "SEER", value: "17.03" },
      { label: "ขนาดเครื่องภายใน (กว้าง × สูง × ลึก)", value: "1,050 × 330 × 1,050 มม." },
      { label: "ขนาดเครื่องภายนอก (กว้าง × สูง × ลึก)", value: "950 × 834 × 330 มม." },
      { label: "ไฟฟ้า", value: "220 โวลต์ 1 เฟส" },
      { label: "ระดับประหยัดพลังงาน", value: "2 ดาว" },
      { label: "สารทำความเย็น", value: "R32" },
    ],
  ),
  AS10GDBY0: verifiedRecord("https://www.lg.com/th/air-puricare/puricare-360/as10gdby0/", "AS10GDBY0", [
    { label: "พื้นที่แนะนำ", value: "104.0 ตร.ม." },
    { label: "ค่า CADR", value: "810 ลบ.ม./ชม." },
    { label: "ขนาด (กว้าง × สูง × ลึก)", value: "377 × 1,100 × 377 มม." },
    { label: "น้ำหนัก", value: "20.6 กก." },
    { label: "กำลังไฟฟ้า", value: "72 วัตต์" },
    { label: "ระดับเสียงสูง / ต่ำ", value: "53 / 26 เดซิเบล" },
    { label: "แผ่นกรอง", value: "H13 Dual V-Pet Filter" },
    { label: "การเชื่อมต่อ", value: "UVnano และ LG ThinQ (Wi-Fi)" },
  ]),
  AS65GDBY0: verifiedRecord("https://www.lg.com/th/air-puricare/puricare-360/as65gdby0/", "AS65GDBY0", [
    { label: "พื้นที่แนะนำ", value: "61.2 ตร.ม." },
    { label: "ค่า CADR", value: "478 ลบ.ม./ชม." },
    { label: "ขนาด (กว้าง × สูง × ลึก)", value: "347 × 612 × 347 มม." },
    { label: "น้ำหนัก", value: "12.5 กก." },
    { label: "กำลังไฟฟ้า", value: "48 วัตต์" },
    { label: "ระดับเสียงสูง / ต่ำ", value: "53 / 26 เดซิเบล" },
    { label: "มอเตอร์พัดลม", value: "BLDC" },
    { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
  ]),
  AS60GHWG0: verifiedRecord("https://www.lg.com/th/air-puricare/puricare-360/as60ghwg0/", "AS60GHWG0", [
    { label: "พื้นที่แนะนำ", value: "61 ตร.ม." },
    { label: "ค่า CADR", value: "483 ลบ.ม./ชม." },
    { label: "ขนาด (กว้าง × สูง × ลึก)", value: "315 × 511 × 315 มม." },
    { label: "น้ำหนัก", value: "6.75 กก." },
    { label: "กำลังไฟฟ้า", value: "41 วัตต์" },
    { label: "ระดับเสียงสูง / ต่ำ", value: "53 / 25 เดซิเบล" },
    { label: "มอเตอร์พัดลม", value: "BLDC" },
    { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
  ]),
  AS25GCBY0: verifiedRecord("https://www.lg.com/th/air-puricare/puricare-aerotower/as25gcby0/", "AS25GCBY0", [
    { label: "พื้นที่แนะนำ", value: "24.8 ตร.ม." },
    { label: "ค่า CADR", value: "3.22 ลบ.ม./นาที" },
    { label: "ขนาด (กว้าง × สูง × ลึก)", value: "710 × 800 × 422 มม." },
    { label: "น้ำหนัก", value: "11.6 กก." },
    { label: "กำลังไฟฟ้า", value: "52 วัตต์" },
    { label: "ระดับเสียงสูง / ต่ำ", value: "52 / 21 เดซิเบล" },
    { label: "มอเตอร์พัดลม", value: "BLDC" },
    { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
  ]),
  DD23GMWE1: verifiedRecord("https://www.lg.com/th/dehumidifier/dd23gmwe1/", "DD23GMWE1", [
    { label: "ความสามารถลดความชื้น", value: "23 ลิตร/วัน" },
    { label: "ความสามารถที่ 30°C / RH 80%", value: "40 ลิตร/วัน" },
    { label: "ความจุถังน้ำ", value: "5.0 ลิตร" },
    { label: "ขนาด (กว้าง × สูง × ลึก)", value: "410 × 640 × 210 มม." },
    { label: "น้ำหนัก", value: "16.0 กก." },
    { label: "กำลังไฟฟ้า", value: "379 วัตต์" },
    { label: "ระดับเสียงสูง / ต่ำ", value: "40 / 34 เดซิเบล" },
    { label: "ระบบอัจฉริยะ", value: "UVnano และ LG ThinQ (Wi-Fi)" },
  ]),
  DFC533FV: verifiedRecord("https://www.lg.com/th/dishwasher/dfc533fv/", "DFC533FV", [
    { label: "ความจุ", value: "14 ชุดภาชนะ" },
    { label: "ขนาด (กว้าง × สูง × ลึก)", value: "600 × 850 × 600 มม." },
    { label: "น้ำหนัก", value: "47 กก." },
    { label: "ระดับเสียง", value: "44 เดซิเบล" },
    { label: "ปริมาณน้ำต่อรอบ", value: "9.9 ลิตร" },
    { label: "ระบบล้าง", value: "TrueSteam และ QuadWash" },
    { label: "ประตูเปิดอัตโนมัติ", value: "ไม่รองรับ" },
    { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
  ]),
  DFC335HM: verifiedRecord("https://www.lg.com/th/dishwasher/dfc335hm/", "DFC335HM", [
    { label: "ความจุ", value: "14 ชุดภาชนะ" },
    { label: "ขนาด (กว้าง × สูง × ลึก)", value: "600 × 850 × 600 มม." },
    { label: "น้ำหนัก", value: "51 กก." },
    { label: "ระดับเสียง", value: "41 เดซิเบล" },
    { label: "ปริมาณน้ำต่อรอบ", value: "9.5 ลิตร" },
    { label: "ระบบล้าง", value: "TrueSteam และ QuadWash" },
    { label: "ประตูเปิดอัตโนมัติ", value: "รองรับ" },
    { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
  ]),
  MS3032JAS: verifiedRecord(
    "https://www.lg.com/th/microwave-ovens/solo-microwave/ms3032jas/",
    "MS3032JAS.BBKPETH",
    [
      { label: "ประเภท", value: "ไมโครเวฟระบบอุ่นอาหาร" },
      { label: "ความจุ", value: "30 ลิตร" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "508 × 290 × 400 มม." },
      { label: "น้ำหนัก", value: "13.1 กก." },
      { label: "กำลังไมโครเวฟ", value: "900 วัตต์" },
      { label: "กำลังไฟฟ้ารวม", value: "1,350 วัตต์" },
      { label: "แหล่งจ่ายไฟ", value: "220 โวลต์ / 50 เฮิรตซ์" },
      { label: "เทคโนโลยี", value: "EasyClean" },
    ],
  ),
  X257CMEW: verifiedRecord(
    "https://www.lg.com/th/refrigerators/side-by-side-refrigerator/gc-x257cmew/",
    "GC-X257CMEW",
    [
      { label: "ความจุรวม", value: "22.4 คิว" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "913 × 1,790 × 735 มม." },
      { label: "น้ำหนัก", value: "131 กก." },
      { label: "การใช้พลังงาน", value: "850 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "คอมเพรสเซอร์", value: "Smart Inverter Compressor (BLDC)" },
      { label: "InstaView", value: "InstaView Door-in-Door" },
      { label: "ระบบจ่ายน้ำ", value: "ไม่ต้องเดินท่อน้ำ" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  X257CMHW: verifiedRecord(
    "https://www.lg.com/th/refrigerators/side-by-side-refrigerator/gc-x257cmhw/",
    "GC-X257CMHW",
    [
      { label: "ความจุรวม", value: "635 ลิตร" },
      { label: "ความจุช่องแช่แข็ง", value: "190 ลิตร" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "913 × 1,790 × 735 มม." },
      { label: "น้ำหนัก", value: "129 กก." },
      { label: "การใช้พลังงาน", value: "850 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "คอมเพรสเซอร์", value: "Smart Inverter Compressor (BLDC)" },
      { label: "ระบบจ่ายน้ำ", value: "ต้องเดินท่อน้ำ" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  X24FFCRB: verifiedRecord(
    "https://www.lg.com/th/refrigerators/multi-door-refrigerator/gc-x24ffcrb/",
    "GC-X24FFCRB",
    [
      { label: "ความจุรวม", value: "642 ลิตร (22.7 คิว)" },
      { label: "ความจุช่องแช่แข็ง", value: "246 ลิตร" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "914 × 1,792 × 729 มม." },
      { label: "น้ำหนัก", value: "149 กก." },
      { label: "การใช้พลังงาน", value: "800 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "คอมเพรสเซอร์", value: "Smart Inverter Compressor (BLDC)" },
      { label: "InstaView", value: "InstaView Door-in-Door" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  G24FFQKB: verifiedRecord(
    "https://www.lg.com/th/refrigerators/multi-door-refrigerator/gc-g24ffqkb/",
    "GC-G24FFQKB",
    [
      { label: "ความจุรวม", value: "637 ลิตร (22.5 คิว)" },
      { label: "ความจุช่องแช่แข็ง", value: "246 ลิตร" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "914 × 1,792 × 733 มม." },
      { label: "น้ำหนัก", value: "144 กก." },
      { label: "การใช้พลังงาน", value: "711 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "คอมเพรสเซอร์", value: "Smart Inverter Compressor (BLDC)" },
      { label: "InstaView", value: "รองรับ" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  S3MFC: verifiedRecord("https://www.lg.com/th/laundry/styler/s3mfc/", "S3MFC", [
    { label: "ความจุ", value: "เสื้อผ้า 3 ชิ้น + กางเกง 1 ตัว" },
    { label: "ขนาด (กว้าง × สูง × ลึก)", value: "445 × 1,850 × 585 มม." },
    { label: "น้ำหนัก", value: "78 กก." },
    { label: "ระบบดูแลผ้า", value: "TrueSteam" },
    { label: "ระบบแขวน", value: "Moving Hanger" },
    { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
  ]),
  QNED80B: verifiedRecord("https://www.lg.com/th/tv-soundbars/qned-evo/55qned80bsa/", "55QNED80BSA", [
    { label: "ขนาดหน้าจอ", value: "55 นิ้ว" },
    { label: "ประเภทจอ", value: "4K QNED evo Mini LED" },
    { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
    { label: "อัตรารีเฟรช", value: "60Hz (VRR สูงสุด 60Hz)" },
    { label: "ช่อง HDMI", value: "3 ช่อง รองรับ eARC และ ALLM" },
    { label: "Wi-Fi", value: "Wi-Fi 5" },
    { label: "Bluetooth", value: "เวอร์ชัน 5.3" },
    { label: "การใช้พลังงานขณะสแตนด์บาย", value: "ต่ำกว่า 0.5 วัตต์" },
  ]),
  "65NU855BPSA": verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/nano-4k-uhd/65nu855bpsa/",
    "65NU855BPSA",
    [
      { label: "ขนาดหน้าจอ", value: "65 นิ้ว" },
      { label: "ประเภทจอ", value: "NANO 4K UHD" },
      { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
      { label: "อัตรารีเฟรช", value: "60Hz (VRR สูงสุด 60Hz)" },
      { label: "ขนาดไม่รวมขาตั้ง (กว้าง × สูง × ลึก)", value: "1,447 × 838 × 70.8 มม." },
      { label: "ช่อง HDMI", value: "3 ช่อง รองรับ eARC และ ALLM" },
      { label: "Wi-Fi", value: "Wi-Fi 5" },
      { label: "Bluetooth", value: "เวอร์ชัน 5.3" },
    ],
  ),
  "75NU855BPSA": verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/nano-4k-uhd/75nu855bpsa/",
    "75NU855BPSA",
    [
      { label: "ขนาดหน้าจอ", value: "75 นิ้ว" },
      { label: "ประเภทจอ", value: "NANO 4K UHD" },
      { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
      { label: "อัตรารีเฟรช", value: "60Hz (VRR สูงสุด 60Hz)" },
      { label: "ขนาดไม่รวมขาตั้ง (กว้าง × สูง × ลึก)", value: "1,669 × 963 × 72.1 มม." },
      { label: "ช่อง HDMI", value: "3 ช่อง รองรับ eARC และ ALLM" },
      { label: "Wi-Fi", value: "Wi-Fi 5" },
      { label: "Bluetooth", value: "เวอร์ชัน 5.3" },
    ],
  ),
  S95TR: verifiedRecord("https://www.lg.com/th/speakers/home-theater-soundbar/s95tr/", "S95TR", [
    { label: "ระบบเสียง", value: "9.1.5 แชนแนล" },
    { label: "กำลังขับรวม", value: "810 วัตต์" },
    { label: "ขนาดซาวด์บาร์ (กว้าง × สูง × ลึก)", value: "1,250 × 63 × 135 มม." },
    { label: "ขนาดลำโพงหลัง (กว้าง × สูง × ลึก)", value: "159 × 223 × 142 มม." },
    { label: "ขนาดซับวูฟเฟอร์ (กว้าง × สูง × ลึก)", value: "201.7 × 407 × 403 มม." },
    { label: "ช่อง HDMI เข้า / ออก", value: "1 / 1 ช่อง พร้อม eARC" },
    { label: "การเชื่อมต่อไร้สาย", value: "Wi-Fi" },
    { label: "รูปแบบเสียง", value: "Dolby Atmos และ DTS:X" },
  ]),
  S70TY: verifiedRecord("https://www.lg.com/th/speakers/soundbars/s70ty/", "S70TY", [
    { label: "ระบบเสียง", value: "3.1.1 แชนแนล" },
    { label: "กำลังขับรวม", value: "400 วัตต์" },
    { label: "ขนาดซาวด์บาร์ (กว้าง × สูง × ลึก)", value: "950 × 63 × 115 มม." },
    { label: "ช่อง HDMI เข้า / ออก", value: "1 / 1 ช่อง" },
    { label: "HDMI eARC", value: "รองรับ" },
    { label: "รูปแบบเสียง", value: "Dolby Atmos" },
  ]),
  GRAB: verifiedRecord("https://www.lg.com/th/speakers/xboom/grab/", "GRAB", [
    { label: "กำลังขับ", value: "20 W + 10 W" },
    { label: "จำนวนช่อง", value: "1.1 แชนแนล (2Way)" },
    { label: "Bluetooth", value: "เวอร์ชัน 5.4" },
    { label: "กันน้ำ / กันฝุ่น", value: "IP67" },
    { label: "อายุแบตเตอรี่", value: "สูงสุด 20 ชั่วโมง" },
    { label: "ขนาดลำโพง (กว้าง × สูง × ลึก)", value: "211.0 × 71.6 × 70.0 มม." },
    { label: "น้ำหนักสุทธิ", value: "0.7 กก." },
  ]),
  BOUNCE: verifiedRecord("https://www.lg.com/th/speakers/xboom/bounce/", "BOUNCE", [
    { label: "กำลังขับ", value: "30 W + 5 W × 2" },
    { label: "จำนวนช่อง", value: "2.1 แชนแนล (Stereo)" },
    { label: "Bluetooth", value: "เวอร์ชัน 5.4" },
    { label: "กันน้ำ / กันฝุ่น", value: "IP67" },
    { label: "อายุแบตเตอรี่", value: "สูงสุด 30 ชั่วโมง" },
    { label: "ขนาดลำโพง (กว้าง × สูง × ลึก)", value: "272 × 103 × 88 มม." },
    { label: "น้ำหนักสุทธิ", value: "1.42 กก." },
  ]),
  STAGE301: verifiedRecord("https://www.lg.com/th/speakers/party-speakers/stage301/", "STAGE301", [
    { label: "กำลังขับ", value: "120 W" },
    { label: "จำนวนช่อง", value: "2.1 แชนแนล (2Way)" },
    { label: "Bluetooth", value: "เวอร์ชัน 5.3" },
    { label: "กันน้ำ", value: "IPX4" },
    { label: "อายุแบตเตอรี่", value: "สูงสุด 12 ชั่วโมง" },
    { label: "ขนาดลำโพง (กว้าง × สูง × ลึก)", value: "312 × 311 × 282 มม." },
    { label: "น้ำหนักสุทธิ", value: "6.5 กก." },
  ]),
  "StandbyME 2": verifiedRecord("https://www.lg.com/th/lifestyle-screens/stanbyme/27lx6tdga/", "27LX6TDGA", [
    { label: "ขนาดหน้าจอ", value: "27 นิ้ว" },
    { label: "ความละเอียด", value: "QHD 2,560 × 1,440 พิกเซล" },
    { label: "อัตรารีเฟรช", value: "60Hz" },
    { label: "ขนาดจอพร้อมขาตั้ง (กว้าง × สูง × ลึก)", value: "623 × 1,265 × 398 มม." },
    { label: "น้ำหนักจอพร้อมขาตั้ง", value: "15.2 กก." },
    { label: "แบตเตอรี่ในตัว", value: "ใช้งานสูงสุด 4 ชั่วโมง" },
    { label: "พอร์ต", value: "HDMI 1 ช่อง และ USB 3 ช่อง" },
    { label: "การเชื่อมต่อและระบบ", value: "Wi-Fi 5, Bluetooth 5.1 และ webOS 24" },
  ]),
  "A9T-ULTRA": verifiedRecord(
    "https://www.lg.com/th/vacuum-cleaner/cordless-vacuum-cleaner/a9t-ultra/",
    "A9T-ULTRA",
    [
      { label: "แบตเตอรี่", value: "ลิเธียมไอออน 2 ก้อน" },
      { label: "เวลาใช้งานสูงสุดต่อแบตเตอรี่", value: "60 นาที (40 นาทีเมื่อใช้หัวดูดไฟฟ้า)" },
      { label: "เวลาชาร์จ", value: "240 นาที" },
      { label: "ขนาดตัวเครื่อง", value: "260 × 1,120 × 270 มม.; 2.9 กก." },
      { label: "ขนาด All-in-One Tower", value: "255 × 1,009 × 297 มม.; 9.7 กก." },
      { label: "ความจุถังเก็บฝุ่น", value: "0.44 ลิตร / 0.88 ลิตรเมื่อบีบอัด" },
      { label: "ความจุถุงเก็บฝุ่นใน Tower", value: "2.5 ลิตร" },
      { label: "ระบบอัจฉริยะ", value: "Kompressor และ LG ThinQ (Wi-Fi)" },
    ],
  ),
  "A9T-CORE": verifiedRecord(
    "https://www.lg.com/th/vacuum-cleaner/cordless-vacuum-cleaner/a9t-core/",
    "A9T-CORE",
    [
      { label: "แบตเตอรี่", value: "ลิเธียมไอออน 2 ก้อน" },
      { label: "เวลาใช้งานสูงสุดต่อแบตเตอรี่", value: "60 นาที (40 นาทีเมื่อใช้หัวดูดไฟฟ้า)" },
      { label: "เวลาชาร์จ", value: "240 นาที" },
      { label: "ขนาดตัวเครื่อง", value: "260 × 270 × 1,120 มม.; 2.9 กก." },
      { label: "ขนาด All-in-One Tower", value: "255 × 1,009 × 297 มม.; 9.8 กก." },
      { label: "ความจุถังเก็บฝุ่น", value: "0.44 ลิตร / 0.88 ลิตรเมื่อบีบอัด" },
      { label: "ความจุถุงเก็บฝุ่นใน Tower", value: "2.5 ลิตร" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  "A9T-LITE": verifiedRecord(
    "https://www.lg.com/th/vacuum-cleaner/cordless-vacuum-cleaner/a9t-lite/",
    "A9T-LITE",
    [
      { label: "แบตเตอรี่", value: "ลิเธียมไอออน 1 ก้อน" },
      { label: "เวลาใช้งานสูงสุด", value: "60 นาที (40 นาทีเมื่อใช้หัวดูดไฟฟ้า)" },
      { label: "เวลาชาร์จ", value: "240 นาที" },
      { label: "ขนาดตัวเครื่อง", value: "260 × 270 × 1,120 มม.; 2.9 กก." },
      { label: "ขนาด All-in-One Tower", value: "255 × 1,009 × 297 มม.; 9.7 กก." },
      { label: "ความจุถังเก็บฝุ่น", value: "0.44 ลิตร / 0.88 ลิตรเมื่อบีบอัด" },
      { label: "ความจุถุงเก็บฝุ่นใน Tower", value: "2.5 ลิตร" },
      { label: "ระบบอัจฉริยะ", value: "Kompressor และ LG ThinQ (Wi-Fi)" },
    ],
  ),
  WT1410NHEG: verifiedRecord(
    "https://www.lg.com/th/laundry/wash-tower/wt1410nheg/",
    "WT1410NHEG",
    [
      { label: "ความจุซักสูงสุด", value: "14 กก." },
      { label: "ความจุอบสูงสุด", value: "10 กก." },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "600 × 1,655 × 660 มม." },
      { label: "น้ำหนัก", value: "128 กก." },
      { label: "ระบบซัก", value: "AI DD และ TurboWash 360" },
      { label: "ระบบไอน้ำ", value: "Steam" },
      { label: "ระบบอบ", value: "DUAL Inverter Heat Pump" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  WT2116SHEG: verifiedRecord("https://www.lg.com/th/laundry/wash-tower/wt2116sheg/", "WT2116SHEG", [
    { label: "ความจุซักสูงสุด", value: "21 กก." },
    { label: "ความจุอบสูงสุด", value: "16 กก." },
    { label: "ขนาด (กว้าง × สูง × ลึก)", value: "700 × 1,890 × 770 มม." },
    { label: "น้ำหนัก", value: "154 กก." },
    { label: "ระบบซัก", value: "AI DD และ TurboWash 360" },
    { label: "ระบบไอน้ำ", value: "Steam" },
    { label: "ระบบอบ", value: "DUAL Inverter Heat Pump" },
    { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
  ]),
  WT2520NHEG: verifiedRecord("https://www.lg.com/th/laundry/wash-tower/wt2520nheg/", "WT2520NHEG", [
    { label: "ความจุซักสูงสุด", value: "25 กก." },
    { label: "ความจุอบสูงสุด", value: "20 กก." },
    { label: "ขนาด (กว้าง × สูง × ลึก)", value: "700 × 1,890 × 830 มม." },
    { label: "น้ำหนัก", value: "160 กก." },
    { label: "ระบบซัก", value: "AI DD และ TurboWash 360" },
    { label: "ระบบไอน้ำ", value: "Steam" },
    { label: "ระบบอบ", value: "DUAL Inverter Heat Pump" },
    { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
  ]),
  FV1413H4M: verifiedRecord(
    "https://www.lg.com/th/laundry/front-load-washing-machine/fv1413h4m/",
    "FV1413H4M",
    [
      { label: "ความจุซัก", value: "13 กก." },
      { label: "ความจุอบ", value: "8 กก." },
      { label: "ระบบถนอมผ้า", value: "AI DD" },
      { label: "ระบบซักเร็ว", value: "TurboWash" },
      { label: "ระบบไอน้ำ", value: "Steam" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  F2520RNTB: verifiedRecord(
    "https://www.lg.com/th/laundry/front-load-washing-machine/f2520rntb/",
    "F2520RNTB",
    [
      { label: "ความจุซัก", value: "20 กก." },
      { label: "ความจุอบ", value: "10 กก." },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "650 × 780 × 950 มม." },
      { label: "น้ำหนัก", value: "86 กก." },
      { label: "ระบบถนอมผ้า", value: "AI DD" },
      { label: "ระบบไอน้ำ", value: "Steam" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  TX2723ST5J: verifiedRecord(
    "https://www.lg.com/th/laundry/top-load-washing-machine/tx2723st5j/",
    "TX2723ST5J",
    [
      { label: "ประเภท", value: "เครื่องซักผ้าฝาบน" },
      { label: "ความจุซักสูงสุด", value: "23 กก." },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "686 × 1,092 × 721 มม." },
      { label: "น้ำหนัก", value: "59 กก." },
      { label: "ระดับประหยัดพลังงานการซัก", value: "5 ดาว" },
      { label: "มอเตอร์", value: "Inverter Direct Drive" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  WD516AN: verifiedRecord(
    "https://www.lg.com/th/water-purifiers/wd516an-aslplmt/",
    "WD516AN.ASLPLMT",
    [
      { label: "สีของรุ่นอ้างอิง", value: "สีเงิน" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "170 × 419 × 550 มม." },
      { label: "ปริมาณน้ำที่ตั้งไว้", value: "120 / 250 / 500 / 1,000 มล." },
      { label: "อุณหภูมิน้ำ", value: "ร้อน / อุณหภูมิห้อง / เย็น" },
      { label: "ระบบกรอง", value: "UF 4 ขั้นตอน" },
      { label: "ระบบถัง", value: "Tankless" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
      { label: "รับประกันชิ้นส่วนคอมเพรสเซอร์อินเวอร์เตอร์", value: "10 ปี" },
    ],
  ),
  WD518AN: verifiedRecord(
    "https://www.lg.com/th/water-purifiers/wd518an-abgplmt/",
    "WD518AN.ABGPLMT",
    [
      { label: "สีของรุ่นอ้างอิง", value: "Calming Beige" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "168 × 398 × 400 มม." },
      { label: "ปริมาณน้ำที่ตั้งไว้", value: "120 / 250 / 500 / 1,000 มล." },
      { label: "อุณหภูมิน้ำ", value: "ร้อน / อุณหภูมิห้อง / เย็น" },
      { label: "ระบบกรอง", value: "UF 4 ขั้นตอน" },
      { label: "ระบบถัง", value: "Tankless" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
      { label: "รับประกันชิ้นส่วนคอมเพรสเซอร์อินเวอร์เตอร์", value: "10 ปี" },
    ],
  ),
  WD110MN: verifiedRecord(
    "https://www.lg.com/th/water-purifiers/wd110mn/",
    "WD110MN.ABGPLMT",
    [
      { label: "สีของรุ่นอ้างอิง", value: "Calming Beige" },
      { label: "อุณหภูมิน้ำ", value: "อุณหภูมิห้อง" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "132 × 358 × 230 มม." },
      { label: "ปริมาณน้ำที่ตั้งไว้", value: "120 / 250 / 500 / 1,000 มล." },
      { label: "ระบบกรอง", value: "UF 4 ขั้นตอน" },
      { label: "ระบบถัง", value: "Tankless" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  "32U889SA": verifiedRecord("https://www.lg.com/th/monitors/smart-monitors/32u889sa-w/", "32U889SA-W", [
    { label: "ขนาดหน้าจอ", value: "31.5 นิ้ว" },
    { label: "ประเภทพาเนล", value: "IPS แบบสัมผัส" },
    { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
    { label: "อัตรารีเฟรช / เวลาตอบสนอง", value: "60Hz / 5 มิลลิวินาที (GtG)" },
    { label: "ขอบเขตสี", value: "DCI-P3 95% (Typ.)" },
    { label: "พอร์ต", value: "HDMI 2 ช่อง และ USB-C 3 ช่อง" },
    { label: "USB-C Power Delivery", value: "65 วัตต์" },
    { label: "การเชื่อมต่อและขาตั้ง", value: "Wi-Fi, Bluetooth และ Swing Stand แบบมีล้อ" },
  ]),
  FV1413S4M: verifiedRecord(
    "https://www.lg.com/th/laundry/front-load-washing-machine/fv1413s4m/",
    "FV1413S4M",
    [
      { label: "ประเภท", value: "เครื่องซักผ้าฝาหน้า" },
      { label: "ความจุซักสูงสุด", value: "13 กก." },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "600 × 850 × 615 มม." },
      { label: "น้ำหนัก", value: "73 กก." },
      { label: "ระบบถนอมผ้า", value: "AI DD" },
      { label: "ระบบซัก", value: "TurboWash และ Steam" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  L257SFZW: verifiedRecord(
    "https://www.lg.com/th/refrigerators/side-by-side-refrigerator/gc-l257sfzw/",
    "GC-L257SFZW.APYPLMT",
    [
      { label: "ความจุรวม", value: "22.4 คิว" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "913 × 1,790 × 735 มม." },
      { label: "น้ำหนัก", value: "112 กก." },
      { label: "การใช้พลังงาน", value: "702 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "ประเภท", value: "Side-by-Side" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  J257SQZW: verifiedRecord(
    "https://www.lg.com/th/refrigerators/side-by-side-refrigerator/gc-j257sqzw/",
    "GC-J257SQZW.AEPPLMT",
    [
      { label: "ความจุรวม", value: "22.4 คิว" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "913 × 1,790 × 735 มม." },
      { label: "น้ำหนัก", value: "121 กก." },
      { label: "การใช้พลังงาน", value: "830 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "ประเภท", value: "Side-by-Side" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  V22FFQMB: verifiedRecord(
    "https://www.lg.com/th/refrigerators/multi-door-refrigerator/gc-v22ffqmb/",
    "GC-V22FFQMB.AEPPLMT",
    [
      { label: "ความจุรวม", value: "18.7 คิว (530 ลิตร)" },
      { label: "ความจุช่องแช่แข็ง", value: "209 ลิตร" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "835 × 1,787 × 730 มม." },
      { label: "น้ำหนัก", value: "110 กก." },
      { label: "การใช้พลังงาน", value: "612 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  B48FPGAM: verifiedRecord(
    "https://www.lg.com/th/refrigerators/multi-door-refrigerator/gc-b48fpgam/",
    "GC-B48FPGAM.ADBPLMT",
    [
      { label: "ความจุรวม", value: "17.4 คิว (502 ลิตร)" },
      { label: "ความจุช่องแช่แข็ง", value: "176 ลิตร" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "830 × 1,855 × 698 มม." },
      { label: "น้ำหนัก", value: "94 กก." },
      { label: "การใช้พลังงาน", value: "604 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "LG ThinQ (Wi-Fi)", value: "ไม่รองรับ" },
    ],
  ),
  "GV-V25FFGRB": verifiedRecord(
    "https://www.lg.com/th/refrigerators/multi-door-refrigerator/gv-v25ffgrb/",
    "GV-V25FFGRB.ABMPLMT",
    [
      { label: "ความจุรวม", value: "21.8 คิว (617 ลิตร)" },
      { label: "ความจุช่องแช่แข็ง", value: "176 ลิตร" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "835 × 1,860 × 736 มม." },
      { label: "น้ำหนัก", value: "119 กก." },
      { label: "การใช้พลังงาน", value: "844 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  "GN-F452PQAK": verifiedRecord(
    "https://www.lg.com/th/refrigerators/2-door-refrigerator/gn-f452pqak/",
    "GN-F452PQAK.AEPPLMT",
    [
      { label: "ประเภท", value: "ตู้เย็น 2 ประตู แช่แข็งบน" },
      { label: "ความจุรวม", value: "16.2 คิว" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "700 × 1,845 × 725 มม." },
      { label: "น้ำหนัก", value: "73 กก." },
      { label: "การใช้พลังงาน", value: "435 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  "GN-V389FQEF": verifiedRecord(
    "https://www.lg.com/th/refrigerators/2-door-refrigerator/gn-v389fqef/",
    "GN-V389FQEF.AEPPLMT",
    [
      { label: "ประเภท", value: "ตู้เย็น 2 ประตู Instaview แช่แข็งล่าง" },
      { label: "ความจุรวม", value: "12 คิว (340 ลิตร)" },
      { label: "ความจุช่องแช่แข็ง", value: "87 ลิตร" },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "600 × 1,720 × 720 มม." },
      { label: "น้ำหนัก", value: "81 กก." },
      { label: "การใช้พลังงาน", value: "445 กิโลวัตต์-ชั่วโมง/ปี" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  WT2520NHEN: verifiedRecord(
    "https://www.lg.com/th/laundry/wash-tower/wt2520nhen/",
    "WT2520NHEN.ABNPETH",
    [
      { label: "ความจุซักสูงสุด", value: "25 กก." },
      { label: "ความจุอบสูงสุด", value: "20 กก." },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "700 × 1,890 × 830 มม." },
      { label: "ระบบซัก", value: "AI DD และ TurboWash 360" },
      { label: "ระบบไอน้ำ", value: "Steam" },
      { label: "ระบบอบ", value: "DUAL Inverter Heat Pump" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  WT1410NHEN: verifiedRecord(
    "https://www.lg.com/th/laundry/wash-tower/wt1410nhen/",
    "WT1410NHEN.ABNPQTH",
    [
      { label: "ความจุซักสูงสุด", value: "14 กก." },
      { label: "ความจุอบสูงสุด", value: "10 กก." },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "600 × 1,655 × 660 มม." },
      { label: "สี", value: "Navy / Beige" },
      { label: "ระบบซัก", value: "AI DD และ TurboWash 360" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  TX2315DT5G: verifiedRecord(
    "https://www.lg.com/th/laundry/top-load-washing-machine/tx2315dt5g/",
    "TX2315DT5G.DEGPETH",
    [
      { label: "ประเภท", value: "เครื่องซักผ้าฝาบน" },
      { label: "ความจุซักสูงสุด", value: "15 กก." },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "590 × 1,043 × 645 มม." },
      { label: "มอเตอร์", value: "Inverter Direct Drive" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  RV10VHP2B: verifiedRecord(
    "https://www.lg.com/th/laundry/dryer/rv10vhp2b/",
    "RV10VHP2B.BBLPETH",
    [
      { label: "ประเภท", value: "เครื่องอบผ้า" },
      { label: "ความจุอบสูงสุด", value: "10 กก." },
      { label: "ขนาด (กว้าง × สูง × ลึก)", value: "600 × 850 × 660 มม." },
      { label: "น้ำหนัก", value: "58 กก." },
      { label: "ระบบอบ", value: "DUAL Inverter Heat Pump" },
      { label: "LG ThinQ (Wi-Fi)", value: "รองรับ" },
    ],
  ),
  OLED77C6PSA: verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/oled-evo/oled77c6psa/",
    "OLED77C6PSA",
    [
      { label: "ขนาดหน้าจอ", value: "77 นิ้ว" },
      { label: "ประเภทจอ", value: "4K OLED" },
      { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
      { label: "ขนาดไม่รวมขาตั้ง (กว้าง × สูง × ลึก)", value: "1,711 × 982 × 47.1 มม." },
      { label: "น้ำหนักไม่รวมขาตั้ง", value: "23.5 กก." },
      { label: "ช่อง HDMI", value: "4 ช่อง รองรับ 4K 120Hz, eARC, VRR, ALLM" },
    ],
  ),
  OLED65C6PSA: verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/oled-evo/oled65c6psa/",
    "OLED65C6PSA",
    [
      { label: "ขนาดหน้าจอ", value: "65 นิ้ว" },
      { label: "ประเภทจอ", value: "4K OLED" },
      { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
      { label: "ขนาดไม่รวมขาตั้ง (กว้าง × สูง × ลึก)", value: "1,441 × 826 × 45.1 มม." },
      { label: "น้ำหนักไม่รวมขาตั้ง", value: "16.6 กก." },
      { label: "ช่อง HDMI", value: "4 ช่อง รองรับ 4K 120Hz, eARC, VRR, ALLM" },
    ],
  ),
  OLED55C6PSA: verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/oled-evo/oled55c6psa/",
    "OLED55C6PSA",
    [
      { label: "ขนาดหน้าจอ", value: "55 นิ้ว" },
      { label: "ประเภทจอ", value: "4K OLED" },
      { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
      { label: "ขนาดไม่รวมขาตั้ง (กว้าง × สูง × ลึก)", value: "1,222 × 703 × 45.1 มม." },
      { label: "น้ำหนักไม่รวมขาตั้ง", value: "14.1 กก." },
      { label: "ช่อง HDMI", value: "4 ช่อง รองรับ 4K 120Hz, eARC, VRR, ALLM" },
    ],
  ),
  "OLED77C6PSA.S80TY": verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/oled-evo/oled77c6psa/",
    "OLED77C6PSA.S80TY",
    [
      { label: "ชุดสินค้า", value: "OLED77C6PSA + ซาวด์บาร์ S80TY" },
      { label: "ขนาดหน้าจอ", value: "77 นิ้ว OLED 4K" },
      { label: "ซาวด์บาร์", value: "S80TY 480 วัตต์" },
      { label: "ขนาดซาวด์บาร์", value: "1,000 × 63 × 135 มม." },
      { label: "ขนาดซับวูฟเฟอร์", value: "201.7 × 407 × 403 มม." },
    ],
  ),
  "OLED65C6PSA.S80TY": verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/oled-evo/oled65c6psa/",
    "OLED65C6PSA.S80TY",
    [
      { label: "ชุดสินค้า", value: "OLED65C6PSA + ซาวด์บาร์ S80TY" },
      { label: "ขนาดหน้าจอ", value: "65 นิ้ว OLED 4K" },
      { label: "ซาวด์บาร์", value: "S80TY 480 วัตต์" },
      { label: "ขนาดซาวด์บาร์", value: "1,000 × 63 × 135 มม." },
      { label: "ขนาดซับวูฟเฟอร์", value: "201.7 × 407 × 403 มม." },
    ],
  ),
  "OLED55C6PSA.S30A": verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/oled-evo/oled55c6psa/",
    "OLED55C6PSA.S30A",
    [
      { label: "ชุดสินค้า", value: "OLED55C6PSA + ซาวด์บาร์ S30A" },
      { label: "ขนาดหน้าจอ", value: "55 นิ้ว OLED 4K" },
      { label: "ซาวด์บาร์", value: "S30A 150 วัตต์" },
      { label: "ขนาดซาวด์บาร์", value: "720 × 63 × 80 มม." },
      { label: "ขนาดซับวูฟเฟอร์", value: "220 × 345 × 220 มม." },
    ],
  ),
  "65QNED80BSA": verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/qned-evo/65qned80bsa/",
    "65QNED80BSA",
    [
      { label: "ขนาดหน้าจอ", value: "65 นิ้ว" },
      { label: "ประเภทจอ", value: "4K QNED Mini LED" },
      { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
      { label: "ขนาดไม่รวมขาตั้ง (กว้าง × สูง × ลึก)", value: "1,455 × 841 × 67.9 มม." },
      { label: "น้ำหนักไม่รวมขาตั้ง", value: "16.5 กก." },
      { label: "ช่อง HDMI", value: "3 ช่อง รองรับ eARC และ ALLM" },
    ],
  ),
  "85QNED80BSA": verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/qned-evo/85qned80bsa/",
    "85QNED80BSA",
    [
      { label: "ขนาดหน้าจอ", value: "85 นิ้ว" },
      { label: "ประเภทจอ", value: "4K QNED Mini LED" },
      { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
      { label: "ขนาดไม่รวมขาตั้ง (กว้าง × สูง × ลึก)", value: "1,889 × 1,087 × 67.0 มม." },
      { label: "น้ำหนักไม่รวมขาตั้ง", value: "27.9 กก." },
      { label: "ช่อง HDMI", value: "3 ช่อง รองรับ eARC และ ALLM" },
    ],
  ),
  "100QNED86BS": verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/qned-evo/100qned86bs/",
    "100QNED86BS",
    [
      { label: "ขนาดหน้าจอ", value: "100 นิ้ว" },
      { label: "ประเภทจอ", value: "4K QNED Mini LED" },
      { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
      { label: "ขนาดไม่รวมขาตั้ง (กว้าง × สูง × ลึก)", value: "2,230 × 1,277 × 49.9 มม." },
      { label: "น้ำหนักไม่รวมขาตั้ง", value: "65.9 กก." },
      { label: "ช่อง HDMI", value: "4 ช่อง รองรับ 4K 120Hz, eARC, VRR, ALLM" },
    ],
  ),
  "100MRGB96BS": verifiedRecord(
    "https://www.lg.com/th/tv-soundbars/micro-rgb-evo/100mrgb96bs/",
    "100MRGB96BS.ATM",
    [
      { label: "ขนาดหน้าจอ", value: "100 นิ้ว" },
      { label: "ประเภทจอ", value: "4K Micro RGB" },
      { label: "ความละเอียด", value: "3,840 × 2,160 พิกเซล" },
      { label: "ขนาดไม่รวมขาตั้ง (กว้าง × สูง × ลึก)", value: "2,230 × 1,277 × 49.9 มม." },
      { label: "ช่อง HDMI", value: "4 ช่อง รองรับ 4K 120Hz, eARC, VRR, ALLM" },
      { label: "การใช้พลังงานขณะสแตนด์บาย", value: "ต่ำกว่า 0.5 วัตต์" },
    ],
  ),
  "32LX6BDGA": verifiedRecord(
    "https://www.lg.com/th/lifestyle-screens/stanbyme/32lx6bdga/",
    "32LX6BDGA.ATM",
    [
      { label: "ขนาดหน้าจอ", value: "32 นิ้ว" },
      { label: "ความละเอียด", value: "4K UHD 3,840 × 2,160 พิกเซล" },
      { label: "ขนาดจอ (กว้าง × สูง × ลึก)", value: "724 × 421 × 28.5 มม." },
      { label: "ช่อง HDMI", value: "1 ช่อง รองรับ eARC" },
      { label: "USB", value: "4 ช่อง" },
      { label: "ระบบ", value: "จอไลฟ์สไตล์ถอดและแขวนได้" },
    ],
  ),
  "45GX950A-B": verifiedRecord(
    "https://www.lg.com/th/monitors/gaming/45gx950a-b/",
    "45GX950A-B.ATM",
    [
      { label: "ขนาดหน้าจอ", value: "45 นิ้ว" },
      { label: "ประเภทพาเนล", value: "OLED Dual-Mode" },
      { label: "ความละเอียด", value: "5K2K (5,120 × 2,160)" },
      { label: "เวลาตอบสนอง", value: "0.03 มิลลิวินาที (GtG)" },
      { label: "HDR", value: "DisplayHDR True Black 400" },
      { label: "พอร์ต", value: "DisplayPort 2.1, HDMI และ USB-C 90 วัตต์" },
    ],
  ),
  "52G930B-B": verifiedRecord(
    "https://www.lg.com/th/monitors/gaming/52g930b-b/",
    "52G930B-B.ATM",
    [
      { label: "ขนาดหน้าจอ", value: "52 นิ้ว" },
      { label: "รูปแบบหน้าจอ", value: "UltraWide 21:9" },
      { label: "ความละเอียด", value: "5K2K" },
      { label: "อัตรารีเฟรชสูงสุด", value: "240Hz" },
      { label: "HDMI", value: "2 ช่อง HDMI 2.1" },
      { label: "USB-C Power Delivery", value: "90 วัตต์" },
    ],
  ),
  "40U990A-W": verifiedRecord(
    "https://www.lg.com/th/monitors/uhd-4k-5k/40u990a-w/",
    "40U990A-W.ATM",
    [
      { label: "ขนาดหน้าจอ", value: "40 นิ้ว" },
      { label: "ประเภทพาเนล", value: "Nano IPS Black 5K2K" },
      { label: "พอร์ต", value: "Thunderbolt 5 และ HDMI 2 ช่อง" },
      { label: "USB-C", value: "1 upstream / 4 downstream" },
      { label: "ขนาดรวมขาตั้ง (กว้าง × สูง × ลึก)", value: "947.7 × 614.3 × 260 มม." },
    ],
  ),
  "34U650A-B": verifiedRecord(
    "https://www.lg.com/th/monitors/",
    "34U650A-B.ATM",
    [
      { label: "ขนาดหน้าจอ", value: "34 นิ้ว" },
      { label: "ความละเอียด", value: "WQHD" },
      { label: "ประเภทพาเนล", value: "IPS โค้ง 3800R" },
      { label: "อัตรารีเฟรชสูงสุด", value: "100Hz" },
      { label: "ขนาดรวมขาตั้ง (กว้าง × สูง × ลึก)", value: "816.7 × 535.2 × 230 มม." },
    ],
  ),
  "32U889SA.GRAB": verifiedRecord(
    "https://www.lg.com/th/monitors/smart-monitors/32u889sa-w/",
    "32U889.GRAB",
    [
      { label: "ชุดสินค้า", value: "32U889SA-W + xboom Grab" },
      { label: "ขนาดหน้าจอ", value: "31.5 นิ้ว IPS แบบสัมผัส 4K" },
      { label: "ลำโพง", value: "LG xboom Grab กันน้ำ IP67" },
      { label: "ขาตั้ง", value: "Swing Stand แบบมีล้อ" },
      { label: "ขนาดรวมขาตั้ง (กว้าง × สูง × ลึก)", value: "727.4 × 1,312.3 × 420 มม." },
    ],
  ),
  "27LX6TDGA.GRAB": verifiedRecord(
    "https://www.lg.com/th/lifestyle-screens/stanbyme/27lx6tdga/",
    "27LX6TDGA.GRAB",
    [
      { label: "ชุดสินค้า", value: "27LX6TDGA + xboom Grab" },
      { label: "ขนาดหน้าจอ", value: "27 นิ้ว QHD" },
      { label: "ลำโพง", value: "LG xboom Grab กันน้ำ IP67" },
      { label: "แบตเตอรี่ในตัว", value: "ใช้งานสูงสุด 4 ชั่วโมง" },
      { label: "ระบบ", value: "webOS และพกพาได้" },
    ],
  ),
};

function normalizeModel(model: string) {
  return model.trim().toUpperCase().replace(/\s+/g, " ");
}

const productSpecificationModelLookup = new Map<string, string>();

for (const [catalogModel, record] of Object.entries(productSpecificationRecords)) {
  productSpecificationModelLookup.set(normalizeModel(catalogModel), catalogModel);
  productSpecificationModelLookup.set(normalizeModel(record.sourceModel), catalogModel);
}

for (const [alias, catalogModel] of Object.entries({
  "WD516AN.ASLPLMT": "WD516AN",
  "WD518AN.ABGPLMT": "WD518AN",
  "WD110MN.ABGPLMT": "WD110MN",
  "65NU855B": "65NU855BPSA",
  "75NU855B": "75NU855BPSA",
  STANBYME2: "StandbyME 2",
  "STANBYME 2": "StandbyME 2",
  "GRAB.ATHALBK": "GRAB",
  "BOUNCE.ATHALBK": "BOUNCE",
  "STAGE301.ATHALBK": "STAGE301",
  "STAGE 301": "STAGE301",
  "ART13A.SR1": "ART13A",
  "ART18A.SR1": "ART18A",
  "ZT4Q18GPLA1.EWGHATH": "ZT4Q18GPLA1",
  "ZT4Q24GPLA1.EWGHATH": "ZT4Q24GPLA1",
  "ZT4Q36GNLA1.EWGHATH": "ZT4Q36GNLA1",
  "ZT4Q48GMLA1.EWGHATH": "ZT4Q48GMLA1",
  "ZT1Q12GULA1.EWGHATH": "ZT1Q12GULA1",
  "ZT1Q18GTLA1.EWGHATH": "ZT1Q18GTLA1",
  "ZT1Q24GTLA1.EWGHATH": "ZT1Q24GTLA1",
  "ZTRQ36GYLA1.EWGHATH": "ZTRQ36GYLA1",
  "ZTRQ48GYLA1.EWGHATH": "ZTRQ48GYLA1",
  "GC-L257SFZW.APYPLMT": "L257SFZW",
  "GC-J257SQZW.AEPPLMT": "J257SQZW",
  "GC-V22FFQMB.AEPPLMT": "V22FFQMB",
  "GC-B48FPGAM.ADBPLMT": "B48FPGAM",
  "GV-V25FFGRB.ABMPLMT": "GV-V25FFGRB",
  "GN-F452PQAK.AEPPLMT": "GN-F452PQAK",
  "GN-V389FQEF.AEPPLMT": "GN-V389FQEF",
  "100MRGB96BS.ATM": "100MRGB96BS",
  "32LX6BDGA.ATM": "32LX6BDGA",
  "45GX950A-B.ATM": "45GX950A-B",
  "52G930B-B.ATM": "52G930B-B",
  "40U990A-W.ATM": "40U990A-W",
  "34U650A-B.ATM": "34U650A-B",
})) {
  productSpecificationModelLookup.set(normalizeModel(alias), catalogModel);
}

export function getProductSpecificationRecord(model: string) {
  const catalogModel = productSpecificationModelLookup.get(normalizeModel(model));
  return catalogModel ? productSpecificationRecords[catalogModel] : undefined;
}
