#!/usr/bin/env python3
"""Build starting monthly prices from Price list_Aug_V3.xlsx."""

from __future__ import annotations

import re
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
XLSX = ROOT / "Price list_Aug_V3.xlsx"
OUT = ROOT / "lib" / "subscription-starting-prices.ts"
CATALOG = ROOT / "lib" / "catalog-products.ts"
SITE = ROOT / "lib" / "site.ts"


def norm(value: str) -> str:
    return re.sub(r"[^A-Z0-9]", "", (value or "").upper())


CATALOG_EXCEL_ALIASES = {
    "DFC533FV": ["PTODFC553FV", "DFC533FV"],
    "X24FFCRB": ["PTOL24FFCBB", "GC-L24FFCBB", "L24FFCBB", "GC-X24FFCRB"],
}


def excel_keys(code: str) -> set[str]:
    keys: set[str] = set()
    for part in re.split(r"[/]", code or ""):
        base = part.strip().split(".")[0].strip()
        if not base:
            continue
        keys.add(norm(base))
        if base.upper().startswith("GC-"):
            keys.add(norm(base[3:]))
        if base.upper().startswith("PTO"):
            keys.add(norm(base[3:]))
    return keys


def catalog_keys(model: str, official_model: str | None) -> set[str]:
    keys = {norm(model)}
    if official_model:
        keys.add(norm(official_model))
    if not model.upper().startswith("GC-"):
        keys.add(norm(f"GC-{model}"))
    specials = {
        "GRAB": {"LGXBOOMGRAB", "XBOOMGRAB"},
        "BOUNCE": {"LGXBOOMBOUNCE", "XBOOMBOUNCE"},
        "STAGE301": {"LGXBOOMSTAGE301", "XBOOMSTAGE301"},
        "STANDBYME2": {"27LX6TDGA"},
    }
    keys |= specials.get(norm(model), set())
    for alias in CATALOG_EXCEL_ALIASES.get(model, []):
        keys.add(norm(alias))
    return {key for key in keys if key}


def keys_match(product_keys: set[str], row_keys: set[str]) -> bool:
    if product_keys & row_keys:
        return True
    for product_key in product_keys:
        if len(product_key) < 6:
            continue
        for row_key in row_keys:
            extra = row_key[len(product_key) :] if row_key.startswith(product_key) else ""
            if extra and len(extra) <= 2 and extra.isalpha():
                return True
    return False


def parse_catalog_models() -> list[tuple[str, str | None]]:
    text = CATALOG.read_text()
    models: list[tuple[str, str | None]] = []
    for match in re.finditer(
        r'^\s{2}(?:"(?P<quoted>[^"]+)"|(?P<bare>[A-Z0-9][A-Z0-9-]*)):\s*\{(?P<body>.*?)^\s{2}\},',
        text,
        re.M | re.S,
    ):
        model = (match.group("quoted") or match.group("bare")).strip()
        official = re.search(r'officialModel:\s*"([^"]+)"', match.group("body"))
        models.append((model, official.group(1) if official else None))
    return models


def parse_featured_models() -> list[str]:
    return re.findall(r'model:\s*"([^"]+)"', SITE.read_text())


def starting_candidates(row: dict) -> list[float]:
    values: list[float] = []
    for key in ("ราคาโปร_รอบบิล1", "ราคาปกติต่อเดือน"):
        raw = row.get(key)
        if isinstance(raw, (int, float)):
            values.append(float(raw))
    span = str(row.get("ช่วงราคาโปร") or "")
    values.extend(float(num) for num in re.findall(r"=(\d+(?:\.\d+)?)", span))
    return [value for value in values if value > 0]


def load_subscription_rows() -> list[dict]:
    workbook = load_workbook(XLSX, data_only=True)
    sheet = workbook["รายการราคา"]
    headers = [cell.value for cell in next(sheet.iter_rows(min_row=1, max_row=1))]
    index = {header: i for i, header in enumerate(headers)}
    rows: list[dict] = []
    for row in sheet.iter_rows(min_row=2, values_only=True):
        item = {header: row[i] for header, i in index.items()}
        if str(item.get("แบบการขาย") or "").lower() != "subscription":
            continue
        rows.append(item)
    return rows


def main() -> None:
    rows = load_subscription_rows()
    wanted = dict.fromkeys([*parse_catalog_models(), *[(model, None) for model in parse_featured_models()]])
    prices: dict[str, int] = {}
    unmatched: list[str] = []

    for model, official in wanted:
        product_keys = catalog_keys(model, official)
        hits = [row for row in rows if keys_match(product_keys, excel_keys(str(row.get("รุ่น") or "")))]
        candidates: list[float] = []
        for row in hits:
            candidates.extend(starting_candidates(row))
        if not candidates:
            unmatched.append(model)
            continue
        prices[model] = int(min(candidates))

    lines = [
        "/** Starting monthly prices from Price list_Aug_V3.xlsx. Regenerated by scripts/extract-subscription-starting-prices.py */",
        "export const subscriptionStartingPrices = {",
        *[f"  {key!r}: {price}," for key, price in prices.items()],
        "} as const;",
        "",
        "/** Campaign first-bill / cheapest package in that category when the exact SKU is not in the workbook. */",
        "export const categoryStartingFallbacks = {",
        '  เครื่องปรับอากาศ: 149,',
        '  เครื่องฟอกอากาศ: 149,',
        '  เครื่องลดความชื้น: 149,',
        '  เครื่องล้างจาน: 149,',
        '  ไมโครเวฟ: 89,',
        '  ตู้เย็น: 149,',
        '  ตู้ถนอมผ้า: 149,',
        '  "ทีวีและเครื่องเสียง": 549,',
        '  ลำโพง: 109,',
        '  เครื่องดูดฝุ่น: 149,',
        '  เครื่องซักผ้าและอบผ้า: 149,',
        '  เครื่องกรองน้ำ: 149,',
        '  จอมอนิเตอร์: 399,',
        "} as const;",
        "",
        "export function getSubscriptionStartingPrice(model: string, category?: string): number | null {",
        "  const exact = subscriptionStartingPrices[model as keyof typeof subscriptionStartingPrices];",
        "  if (exact !== undefined) return exact;",
        "  if (!category) return null;",
        "  return categoryStartingFallbacks[category as keyof typeof categoryStartingFallbacks] ?? null;",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(prices)} prices to {OUT.relative_to(ROOT)}")
    if unmatched:
        print("unmatched:", ", ".join(unmatched))


if __name__ == "__main__":
    main()
